apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flightline-secrets
spec:
  refreshInterval: 1h
  secretStoreRef: { kind: ClusterSecretStore, name: aws-secrets-manager }
  target: { name: flightline-secrets }
  data:
    - secretKey: pagerduty-routing-key
      remoteRef: { key: flightline/pagerduty, property: routing_key }
    - secretKey: slack-webhook-url
      remoteRef: { key: flightline/slack, property: webhook_url }
    - secretKey: api-keys
      remoteRef: { key: flightline/ingest, property: api_keys_json }
